apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: fv-kind
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /Users/stephen.cahill/Desktop/dev-projects/funvue-pr/funvue-project/local-kind/fortune-teller-mysql
        containerPath: /mount
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
    extraPortMappings:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    - containerPort: 443
      hostPort: 443
      protocol: TCP