targetSystem: "linux"
datadog:
  apm:
    portEnabled: true
  securityContext: {}
  hostVolumeMountPropagation: None
  logLevel: DEBUG
  clusterName: fv
  kubeStateMetricsEnabled: false
  kubeStateMetricsCore:
    enabled: true
  kubelet:
    host:
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    tlsVerify: false
  ignoreAutoConfig:
  - etcd
  - kube_scheduler
  - kube_controller_manager
  confd:
    etcd.yaml: |-
      ad_identifiers:
        - etcd
      instances:
        - prometheus_url: https://%%host%%:2379/metrics
          tls_ca_cert: /host/etc/kubernetes/pki/etcd/ca.crt
          tls_cert: /host/etc/kubernetes/pki/etcd/server.crt
          tls_private_key: /host/etc/kubernetes/pki/etcd/server.key
    kube_scheduler.yaml: |-
      ad_identifiers:
        - kube-scheduler
      instances:
        - prometheus_url: https://%%host%%:10259/metrics
          ssl_verify: false
          bearer_token_auth: true
    kube_controller_manager.yaml: |-
      ad_identifiers:
        - kube-controller-manager
      instances:
        - prometheus_url: https://%%host%%:10257/metrics
          ssl_verify: false
          bearer_token_auth: true
  dogstatsd:
    port: 8125
    originDetection: true
    tags: []
    tagCardinality: high
    useSocketVolume: true
    socketPath: /var/run/datadogs1/dsd.socket
    hostSocketPath: /var/run/datadogs1/
    useHostPort: true
    useHostPID: true
    nonLocalTraffic: true
  collectEvents: true
  leaderElection: true
  logs:
    enabled: true
    containerCollectAll: true
    containerCollectUsingFiles: true
  env: 
    - name: DD_TELEMETRY_ENABLED
      value: true
    - name: DD_ENV
      value: dev
    - name: DD_HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  processAgent:
    enabled: true
    processCollection: true
agents:
  image:
    tag: 7-jmx
  volumes:
    - hostPath:
        path: /etc/kubernetes/pki/etcd
      name: etcd-certs
  volumeMounts:
    - name: etcd-certs
      mountPath: /host/etc/kubernetes/pki/etcd
      readOnly: true
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists