version: '3'
services:
    # ddagent:
    #   image: datadog/agent:latest
    #   container_name: datadog-agent-ft
    #   env_file:
    #     - ~/sandbox.docker.env
    #   environment:
    #     - DD_APM_ENABLED=true
    #     - DD_LOGS_ENABLED=true
    #     - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
    #     - DD_APM_NON_LOCAL_TRAFFIC=true
    #     - DD_AC_EXCLUDE=name:datadog-agent-ft
    #   volumes: 
    #     - /var/run/docker.sock:/var/run/docker.sock:ro
    #     - /proc/:/host/proc/:ro
    #     - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    #   ports:
    #     - "8126:8126"
    #   restart: on-failure
    #   depends_on: 
    #     - mysql_db
    master:
      image: locustio/locust
      ports:
      - "8089:8089"
      volumes:
        - ./locust-loadtest:/mnt/locust
      command: -f /mnt/locust/locustfile.py --master -H http://master:8089
    
    worker:
      image: locustio/locust
      volumes:
        - ./locust-loadtest:/mnt/locust
      command: -f /mnt/locust/locustfile.py --worker --master-host master
    mongodb:
      image: mongo
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
      volumes:
    #     - ./fortune-teller-mysql/conf.d:/etc/mysql/conf.d
        - ./mongo-db/mongo-db-init-files:/docker-entrypoint-initdb.d
    #   labels:
    #     com.datadoghq.ad.check_names: '["mysql"]'
    #     com.datadoghq.ad.init_configs: '[{}]'
    #     com.datadoghq.ad.instances: '[{"server": "%%host%%", "user": "datadog","pass": "tacosandburritos"}]'
      ports:
        - '27017:27017'
    # express_server:
    #   build:
    #     dockerfile: Dockerfile
    #     context: ./fortune-teller-express
    #   depends_on: 
    #     - mysql_db
    #   environment: 
    #     - DD_AGENT_HOST=datadog-agent-ft
    #   ports:
    #     - '8080:8080'
    # angular_web:
    #   build:
    #     dockerfile: Dockerfile
    #     context: ./fortune-teller-ng
    #   depends_on: 
    #     - express_server
    #   env_file:
    #     - ~/sandbox.docker.env
    #   ports:
    #     - '4200:4200'